name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/test-chatbot || git clone https://github.com/${{ github.repository }} /home/ubuntu/test-chatbot
          cd /home/ubuntu/test-chatbot
          git pull origin main
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sudo pkill -f "python3 app.py" || true
          nohup python3 app.py > app.log 2>&1 &
          sleep 2
          echo "Deployment complete"